version: "3.9"

services:
 flask_app:
  container_name: flask_app
  build: .
  ports:
   - "4000:4000"
  environment:
   - DB_URL=postgresql://postgres:postgres@flask_db:5432/lb9
  depends_on:
   - flask_db
  networks:
   laba:
  
 flask_db:
  container_name: flask_db
  image: postgres:12
  ports:
   - "5432:5432"
  environment: 
   - POSTGRES_PASSWORD=postgres
   - POSTGRES_USER=postgres
   - POSTGRES_DB=lb9
  volumes:
   - pgdata:/var/lib/postgresql/data
  networks:
   laba:
   
volumes:
 pgdata: {}

networks:
 laba:
  driver: bridge